name: learn-github-actions
on: [push]
jobs:
  test-flow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is pen"
      - uses: actions/checkout@v2
      - run: |
          ls -al
          cd .github/workflows/
          ls -al